@startuml

skinparam linetype ortho

entity "Patient" as pat {
  *NHS Number : number <<generated>>
}

entity "Patient Flag" as pfg {
  *patient : Patient
  *code : CodeableConcept
  *category : CodeableConcept
  *contained : Provenance (Contained)
}

entity "Provenance" as pro {
  *recorded : Date
  *agent : Agent (backbone)
}

pat ||--o| pfg : "has"
pfg ||--|| pro : contains


@enduml
