@startuml

skinparam actorStyle awesome

actor Practitioner as pra
package Consenter {
  actor "Patient Advocate" as pad
  actor Patient as pat
}

usecase "Consent to share information" as CON
usecase "Retrieve Reasonable Adjustment record" as RET

pat -- CON
pad -- CON
pra -- CON
pra -- RET

CON <.. RET : include

@enduml
